---
- name: check value for key name
  set_fact:
    resultado: "{{ resultado + ['Value for key name incorrect: '+ item.name +'. Expected format is ans_country_group_type_name'] }}"
  when: name not in item.keys() or item.name is not match ('^(ans_(ibe|spw|agr|neo|mex)_(linux|win|email|sql|ad|ora|storage|j2ee|mon|dts|ocp)_(p|r|i|c)_([\w_]+))$')
  ignore_errors: true  

- name: check value for key title
  set_fact:
    resultado: "{{ resultado + ['Value for key title incorrect: '+ item.title +'. It should contain a minimum of 10 characters and a maximum of 50'] }}"
  when: title not in item.keys() or item.title is not match ('^.{10,50}$')
  ignore_errors: true

- name: check value for key author
  set_fact:
    resultado: "{{ resultado + ['Value for key author incorrect: '+ item.author +'. Expected format is first and last name or email address'] }}"
  when: author not in item.keys() or item.author is not match ('^[\w_.@\- ]+$')
  ignore_errors: true 

- name: check value for key repository
  set_fact:
    resultado: "{{ resultado + ['Value for key repository incorrect: '+ item.repository +'. It should start with https://'] }}"
  when: repository not in item.keys() or item.repository is not match ('^https:\/\/([\w]+[.][\w]+[\w_\-\/]+)$')
  ignore_errors: true

- name: check value for key description
  set_fact:
    resultado: "{{ resultado + ['Value for key short_description incorrect: '+ item.short_description +'. It should contain a minimum of 25 characters and a maximum of 500'] }}"
  when: short_description not in item.keys() or item.short_description is not match ('^.{25,500}$')
  ignore_errors: true

- name: check value for key tags
  set_fact:
    resultado: "{{ resultado + ['Value for key tags incorrect: '+ item.tags +'. Tags should be separated by ,'] }}"
  when: tags not in item.keys() or item.tags is not match ('^([\w]+,{0,1}[\w]+)+$')
  ignore_errors: true

- name: check value for key date
  set_fact:
    resultado: "{{ resultado + ['Value for key date incorrect: '+ item.date +'. Expected format is YYYY-MM-DD'] }}"
  when: date not in item.keys() or item.date is not match ('^([0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9])$')
  ignore_errors: true

