---
- name: init the variable resultado
  set_fact:
    resultado: []
    name: name
    title: title
    author: author
    repository: repository
    short_description: short_description
    date: date
    tags: tags

- name: check values of all dictionary entries
  include_tasks: format_validation.yml
  loop: "{{ ansible_objects }}" 
