---
git_username: grequenar
git_pass: ""
dict_repo: 
site_repo: "https://{{ git_username }}:{{ git_pass }}@github.com/grequenar/ans_documentation_v2.git"

# yaml_style role
dir_style_check: playbooks

# check_dictionary role
dict_file: ans_doc_dictionary_correct.yml

myip: 192.168.122.11
