# Example usage: ansible-playbook -i ansiblecontroller playbooks/dict_check.yml -vvv --extra-vars "git_pass=***"
# This playbook checks the format of the values assigned to the different keys for each item of the dictionary
---
- name: check
  hosts: localhost
  connection: local
  gather_facts: false
  
  pre_tasks:
# - name: clone of the repo that contains the dictionary
#   git:
#     repo: "https://github.com/grequenar/ans_documentation_data.git"
#     dest: "{{ dict_path }}"
  
  - include_vars:
      dir: ../vars
  
  tasks:
  - name: validate yaml syntax of dictionary
    shell: ansible-lint "{{ dict_path }}/{{ dict_file }}"
 
  - include_vars:
      file: "{{ dict_path }}/{{ dict_file }}"

  - name: validate format of dictionary values
    include_role:
      name: roles/check_dictionary

  - name: print result
    assert:
      that: not resultado
      success_msg: "The result of the format validation is correct."
      fail_msg: "The result of the format validation is incorrect. The following errors were found:\n {{ resultado }}"

