# Example usage: ansible-playbook -i ansiblecontroller playbooks/post_generator.yml -vvv --extra-vars "git_pass=*************"
# This playbook checks the syntax of the dictionary
---
- name: generator of new content after a dictionary update
  hosts: localhost
  connection: local
  gather_facts: false
  
  pre_tasks: 
  - include_vars:
      dir: ../vars
  
  tasks:
  - include_vars:
      file: "{{ dict_path }}/{{ dict_file }}"

  - name: clone of the site repository
    git:
      repo: "https://github.com/grequenar/ans_documentation_v2.git"
      # dest: "{{ site_path }}"
      dest: /tmp/ans_documentation_v2 

  - name: override data base of site with new dictionary
    src: "{{ dict_path }}/{{ dict_file }}"
    dest: "{{ site_path }}/_data/ans_dictionary.yml" 
    force: yes

  - name: create new site content
    include_role:
      name: roles/jekyll_templates
 
