# Example usage: ansible-playbook -i ansiblecontroller playbooks/dict_check.yml -vvv --extra-vars "git_pass=***"
# This playbook validates that the yaml files within the project respect the style rules contemplated on the documentation
---
- name: validate style of yaml files
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: search of yaml files
    find:
      paths: "/home/iberdrola_installer/poc_files_v2/jekyll_automation/{{ dir_style_check }}"
      recurse: true
      patterns: '*.yml,*.yaml'
    register: files_list_yml

  - name: include roles
    include_role:
      name: roles/yaml_style

  - name: print name result
    assert:
      that: not resultado
      success_msg: "El resultado de las validaciones es correcto."
      fail_msg: "El resultado de las validaciones es incorrecto:\n {{ resultado }}"

