# Example usage: ansible-playbook -i ansiblecontroller playbooks/dict_check.yml -vvv --extra-vars "git_pass=***"
# This playbook checks the syntax of the dictionary
---
- name: validate style of playbooks
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: search of yaml files
    find:
      paths: /home/iberdrola_installer/poc_files_v2/playbooks
      recurse: true
      patterns: '*.yml,*.yaml'
    register: files_list_yml

  - name: include roles
    include_role:
      name: yaml_style

  - debug:
      msg: "{{ resultado }}"

  - name: print name result
    assert:
      that: not resultado
      success_msg: "El resultado de las validaciones es correcto"
      fail_msg: "El resultado de la ejecución es incorrecto:\n {{ resultado }}"

