---
- name: delete previous content of site
  include_tasks: site_cleaning.yml 

- name: create new/updated site content
  include_tasks: site_post_building.yml
  # loop: "{{ ansible_objects }}"

- name: push new content to new branch of repository
  include_tasks: site_push.yml 



