- name: git push of new content of site
  git_acp:
    path: "/tmp/ans_documentation_v2"
    branch: master
    comment: "Catalogue content update"
    remote: origin
    add: [ "." ]
    mode: ssh
    url: "git@github.com:grequenar/ans_documentation_v2"
    user_name: grequenar
    user_email: grequena@redhat.com

# el push funciona pero no se si previamente habria que hacer un git rm de los posts en el repo de git, en vez de borrarlos solo en local?
