---
- name: Register all files in the posts directory
  find:
#   paths: "{{ site_path }}"
    paths: /tmp/ans_documentation_v2/_posts
    patterns: 
      - "*.md" 
      - "*.markdown" 
      - "*.html"
  register: files_to_delete

- name: Remove all existing posts but not the directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: remove the posts from git repo
  shell:
    cmd: git rm "{{ item.path }}"
  with_items: "{{ files_to_delete.files }}" 
